[pt-PT] Added rules to .AFFs taken from -BR to -PT 45+90
languagetool-org/portuguese-pos-dict pull request #23
Opened 2024-02-13 18:52 UTC by marcoagpinto

Heya, @susanaboatto  and @p-goulart 

Here is an update of the pt-PT .AFFs “stolen” from pt-BR.

They added around 8 000 conjugations.

[6.PTPT_90_new_verbs.txt](https://github.com/languagetool-org/portuguese-pos-dict/files/14270938/6.PTPT_90_new_verbs.txt)

2024-02-15 06:46 UTC, p-goulart requested changes
This outputs a lot of verbs that we don't want, since the flag is not used only for verbs derived from `ter`. In the file attached to your PR we can see `acometer`, for example.

2024-02-15 06:46 UTC, p-goulart commented on data/spelling-dict/hunspell/pt_PT_45.aff
> +SFX L   0       -nas-�o        ter
`ter-nas`?

2024-02-15 06:46 UTC, p-goulart commented on data/spelling-dict/hunspell/pt_PT_45.aff
> +SFX L   r       ve-as          ter
`teve-as` but no `teve-a`

2024-02-15 06:46 UTC, p-goulart commented on data/spelling-dict/hunspell/pt_PT_45.aff
> +SFX L   r       ve-o           ter
`teve-o` but no `teve-os`

2024-02-15 06:46 UTC, p-goulart commented on data/spelling-dict/hunspell/pt_PT_45.aff
> +SFX L   er      �m-vos         ter
This outputs `tém-se`, etc. These should only be available for derived forms of `ter`, but not `ter` itself.

2024-02-15 06:52 UTC, marcoagpinto commented
@p-goulart 

Ahhhh… thanks for the feedback.

Can the “ter” issues be solved if I add `[aeiou]ter` to `ter`?


Thanks!

2024-02-15 06:56 UTC, p-goulart commented
> Can the “ter” issues be solved if I add `[aeiou]ter` to `ter`?

That won't account for all forms: `conter`, `obter`.

Trusting the Brazilian affix files too much is not wise since the flags are used in fundamentally different ways, with different distributions. It's best to just adapt the `pt-PT` flags.

2024-02-15 07:09 UTC, marcoagpinto commented
Ahhhh… I will fix it tonight… or tomorrow at 5am… right now, I have been up since 3am working on other projects and my brain is drained, and I can't focus on precision things😄 😛 😛 😛 😛 😛 😛 😛 😛 😛 😛 😛

2024-02-16 00:37 UTC, marcoagpinto commented
Heya, @p-goulart 

I have done some enhancements to the .AFFs.

Here are the results of the new AO90 one (new words):
[6.PTPT_90_new_verbs_20240216.txt](https://github.com/languagetool-org/portuguese-pos-dict/files/14303801/6.PTPT_90_new_verbs_20240216.txt)

I have unable to check conjugation by conjugation, so, please, if you find any wrong item, please tell me with a suggestion on how to fix them.

Thanks!

2024-02-21 16:15 UTC, marcoagpinto commented
@p-goulart 

Heya, Pedro, any news regarding this?

Thanks!

2024-02-21 16:21 UTC, p-goulart commented
We can still spot some verb forms that don't make a lot of sense:
- abatém;
- batenha;
- combativesse;
- cometeve.

We know it's an unexciting task, but do you think you could check your work in full yourself and spot the odd ones out?

---

The approach you're taking here is not working because the flags are used differently in the `pt-PT` and `pt-BR` files. Please bear that in mind.

2024-02-21 16:28 UTC, marcoagpinto commented
> We can still spot some verb forms that don't make a lot of sense:
> 
>     * abatém;
> 
>     * batenha;
> 
>     * combativesse;
> 
>     * cometeve.
> 
> 
> We know it's an unexciting task, but do you think you could check your work in full yourself and spot the odd ones out?
> 
> The approach you're taking here is not working because the flags are used differently in the `pt-PT` and `pt-BR` files. Please bear that in mind.

Ahhhh… thanks for the feedback, I will close this pull request and start with smaller rules… I was too greedy and wanted the bullet that cures all, or whatever it is called.

I always liked to make things bit by bit, but I was too greedy.

😋 😋 😋 😋 😋 😋 😋 😋 😋 😋 😋

2024-02-21 16:28 UTC, closed without merging